"""study_logs.hour_update

Revision ID: 1714a54ab229
Revises: 0fcec7a78ed5
Create Date: 2025-09-09 20:08:25.827543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1714a54ab229'
down_revision = '0fcec7a78ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_logs', schema=None) as batch_op:
        batch_op.alter_column('hour',
               existing_type=mysql.DECIMAL(precision=6, scale=1),
               type_=sa.DECIMAL(precision=6, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_logs', schema=None) as batch_op:
        batch_op.alter_column('hour',
               existing_type=sa.DECIMAL(precision=6, scale=2),
               type_=mysql.DECIMAL(precision=6, scale=1),
               existing_nullable=False)

    # ### end Alembic commands ###
