"""study_logsテーブルの修正

Revision ID: 3619554ad7b9
Revises: 75809f62f650
Create Date: 2025-07-19 04:35:34.788510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3619554ad7b9'
down_revision = '75809f62f650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hour', sa.DECIMAL(precision=6, scale=1), nullable=False))
        batch_op.drop_column('hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours', mysql.DECIMAL(precision=6, scale=1), nullable=False))
        batch_op.drop_column('hour')

    # ### end Alembic commands ###
