"""fieldname unique解除

Revision ID: 75809f62f650
Revises: b6cab990b7c3
Create Date: 2025-07-17 08:10:52.053964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75809f62f650'
down_revision = 'b6cab990b7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fieldname'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('fieldname'), ['fieldname'], unique=True)

    # ### end Alembic commands ###
