"""edit all_tables_column

Revision ID: b6cab990b7c3
Revises: 40a1bf8c4369
Create Date: 2025-07-17 06:45:28.874930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6cab990b7c3'
down_revision = '40a1bf8c4369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=False))
        batch_op.alter_column('fieldname',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=20, collation='utf8mb4_general_ci'),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['fieldname'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('fieldname',
               existing_type=sa.String(length=20, collation='utf8mb4_general_ci'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
